# Generated by Django 5.0.6 on 2026-05-17 11:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='🗑️', max_length=50)),
                ('color', models.CharField(default='#4CAF50', max_length=7)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_hazardous', models.BooleanField(default=False)),
                ('requires_special_handling', models.BooleanField(default=False)),
                ('is_recyclable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Waste Categories',
                'db_table': 'waste_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CollectionRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('total_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estimated_duration_mins', models.PositiveIntegerField(blank=True, null=True)),
                ('waypoints', models.JSONField(default=list)),
                ('polyline', models.TextField(blank=True)),
                ('total_stops', models.PositiveIntegerField(default=0)),
                ('completed_stops', models.PositiveIntegerField(default=0)),
                ('fuel_consumed_liters', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'waste_collection_route',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('collected', 'Collected'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], db_index=True, default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('division', models.CharField(blank=True, choices=[('central', 'Central Division'), ('kawempe', 'Kawempe Division'), ('makindye', 'Makindye Division'), ('nakawa', 'Nakawa Division'), ('rubaga', 'Rubaga Division')], db_index=True, max_length=50)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_instructions', models.TextField(blank=True)),
                ('estimated_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('waste_description', models.TextField(blank=True)),
                ('waste_image', models.ImageField(blank=True, null=True, upload_to='waste_images/')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time_start', models.TimeField(blank=True, null=True)),
                ('preferred_time_end', models.TimeField(blank=True, null=True)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(db_index=True, default=False)),
                ('resident_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('resident_feedback', models.TextField(blank=True)),
                ('rated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_requests', to='payments.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='waste.wastecategory')),
            ],
            options={
                'db_table': 'waste_pickup_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route_order', models.PositiveIntegerField(default=0)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time_start', models.TimeField(blank=True, null=True)),
                ('scheduled_time_end', models.TimeField(blank=True, null=True)),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('collector_notes', models.TextField(blank=True)),
                ('collection_image', models.ImageField(blank=True, null=True, upload_to='collection_proof/')),
                ('weight_collected_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_assignments', to=settings.AUTH_USER_MODEL)),
                ('collector', models.ForeignKey(limit_choices_to={'role': 'collector'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='waste.collectionroute')),
                ('pickup_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='waste.pickuprequest')),
            ],
            options={
                'db_table': 'waste_assignment',
            },
        ),
        migrations.CreateModel(
            name='SmartBin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bin_id', models.CharField(max_length=30, unique=True)),
                ('location_name', models.CharField(max_length=200)),
                ('division', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('capacity_liters', models.PositiveIntegerField(default=240)),
                ('fill_level', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('full', 'Full'), ('maintenance', 'Under Maintenance'), ('offline', 'Offline')], default='active', max_length=20)),
                ('last_emptied', models.DateTimeField(blank=True, null=True)),
                ('last_reading', models.DateTimeField(blank=True, null=True)),
                ('sensor_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('waste_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='waste.wastecategory')),
            ],
            options={
                'db_table': 'waste_smart_bin',
            },
        ),
        migrations.CreateModel(
            name='WasteReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_type', models.CharField(choices=[('illegal_dumping', 'Illegal Dumping'), ('overflowing_bin', 'Overflowing Bin'), ('missed_collection', 'Missed Collection'), ('road_blockage', 'Road Blockage'), ('hazardous_waste', 'Hazardous Waste'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('division', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='waste_reports/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'waste_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectorLocationUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('accuracy_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_updates', to='waste.assignment')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'waste_collector_location',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['collector', 'timestamp'], name='waste_colle_collect_fd0741_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['collector', 'scheduled_date'], name='waste_assig_collect_3f9d90_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['scheduled_date'], name='waste_assig_schedul_6470bd_idx'),
        ),
        migrations.AddIndex(
            model_name='smartbin',
            index=models.Index(fields=['division', 'status'], name='waste_smart_divisio_893db1_idx'),
        ),
        migrations.AddIndex(
            model_name='smartbin',
            index=models.Index(fields=['fill_level'], name='waste_smart_fill_le_160908_idx'),
        ),
        migrations.AddIndex(
            model_name='pickuprequest',
            index=models.Index(fields=['status', 'division'], name='waste_picku_status_aeae4e_idx'),
        ),
        migrations.AddIndex(
            model_name='pickuprequest',
            index=models.Index(fields=['user', 'status'], name='waste_picku_user_id_d66f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='pickuprequest',
            index=models.Index(fields=['created_at', 'status'], name='waste_picku_created_bd0534_idx'),
        ),
        migrations.AddIndex(
            model_name='pickuprequest',
            index=models.Index(fields=['preferred_date', 'status'], name='waste_picku_preferr_a2c568_idx'),
        ),
        migrations.AddIndex(
            model_name='pickuprequest',
            index=models.Index(fields=['is_paid', 'status'], name='waste_picku_is_paid_7b3278_idx'),
        ),
    ]
