# Generated by Django 5.0.6 on 2026-05-17 11:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='campaigns/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('ended', 'Ended')], default='draft', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target_division', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recycling_campaign',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecyclingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_type', models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper/Cardboard'), ('glass', 'Glass'), ('metal', 'Metal/Aluminium'), ('electronics', 'E-Waste'), ('organic', 'Organic/Compost'), ('textile', 'Textiles')], max_length=20)),
                ('estimated_weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recycling/')),
                ('address', models.TextField()),
                ('division', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('collected', 'Collected'), ('processed', 'Processed'), ('rewarded', 'Rewarded')], default='pending', max_length=20)),
                ('actual_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('reward_points', models.PositiveIntegerField(default=0)),
                ('reward_paid', models.BooleanField(default=False)),
                ('carbon_saved_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('recycler', models.ForeignKey(blank=True, limit_choices_to={'role': 'recycler'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_recycling', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recycling_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recycling_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardPoints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('earned', 'Earned'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('bonus', 'Bonus')], max_length=10)),
                ('points', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recycling_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recycling.recyclingrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recycling_reward_points',
                'ordering': ['-created_at'],
            },
        ),
    ]
